In [153]:
import numpy as np
import pandas as pd

In [154]:
#Version of NumPy
print(np.__version__)

1.19.5


In [155]:
#Version of Pandas
print(pd.__version__)

1.3.2


In [156]:
df = pd.read_csv('D:\data.csv')
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [157]:
#The average price of BMW
avg_msrp_make =df.groupby('Make').MSRP.mean().round(2)
avg_msrp_make['BMW']

61546.76

In [158]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [159]:
df_after_2015 = df[df['Year'] >=2015]
df_after_2015

Make       Model  Year                Engine Fuel Type  Engine HP  \
32     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41      BMW    2 Series  2016     premium unleaded (required)      240.0   
42      BMW    2 Series  2016     premium unleaded (required)      240.0   
...     ...         ...   ...                             ...        ...   
11898   BMW          Z4  2015     premium unleaded (required)      300.0   
11899   BMW          Z4  2015     premium unleaded (required)      335.0   
11900   BMW          Z4  2016     premium unleaded (required)      300.0   
11901   BMW          Z4  2016     premium unleaded (required)      240.0   
11902   BMW          Z4  2016     premium unleaded (required)      335.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32                  4.0            MANUAL  rear wheel drive              2.0   
33                  4.0            MANUAL  rear wheel drive              2.0   
34                  4.0            MANUAL  rear wheel drive              2.0   
41                  4.0         AUTOMATIC  rear wheel drive              2.0   
42                  4.0         AUTOMATIC  rear wheel drive              2.0   
...                 ...               ...               ...              ...   
11898               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11899               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11900               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11901               4.0            MANUAL  rear wheel drive              2.0   
11902               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   

               Market Category Vehicle Size Vehicle Style  highway MPG  \
32                 Performance      Compact   Convertible           35   
33                 Performance      Compact   Convertible           35   
34                 Performance      Compact   Convertible           35   
41          Luxury,Performance      Compact         Coupe           35   
42                      Luxury      Compact   Convertible           34   
...                        ...          ...           ...          ...   
11898  Luxury,High-Performance      Compact   Convertible           24   
11899  Luxury,High-Performance      Compact   Convertible           24   
11900  Luxury,High-Performance      Compact   Convertible           24   
11901       Luxury,Performance      Compact   Convertible           34   
11902  Luxury,High-Performance      Compact   Convertible           24   

       city mpg  Popularity   MSRP  
32           26         819  27495  
33           26         819  24995  
34           26         819  28195  
41           23        3916  32850  
42           23        3916  38650  
...         ...         ...    ...  
11898        17        3916  56950  
11899        17        3916  65800  
11900        17        3916  57500  
11901        22        3916  49700  
11902        17        3916  66350  

[5995 rows x 16 columns]

In [160]:
# Number of missing values in "Engine HP" after 2015 (including 2015)
df_after_2015['Engine HP'].isnull().sum()

51

In [161]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [162]:
mean_hp_before = df['Engine HP'].mean()
mean_hp_before

249.38607007176023

In [163]:
df['Engine HP']

0        335.0
1        300.0
2        300.0
3        230.0
4        230.0
         ...  
11909    300.0
11910    300.0
11911    300.0
11912    300.0
11913    221.0
Name: Engine HP, Length: 11914, dtype: float64

In [164]:
df_copy = df

In [165]:
df_copy['Engine HP'] = df['Engine HP'].fillna(mean_hp_before)

In [166]:
df_copy['Engine HP'].isnull().sum()

0

In [167]:
mean_hp_after = df_copy['Engine HP'].mean()
mean_hp_after 

249.38607007176023

In [168]:
#Mean change after filling missing values
print(round(mean_hp_before))
print(round(mean_hp_after))

249
249


In [169]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [170]:
Rolls_Royce = df[df['Make'] == 'Rolls-Royce']
Rolls_Royce

Make                   Model  Year             Engine Fuel Type  \
2921   Rolls-Royce                Corniche  2001  premium unleaded (required)   
3505   Rolls-Royce                    Dawn  2016  premium unleaded (required)   
5275   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5276   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5277   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5278   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5279   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5280   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5281   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5282   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5283   Rolls-Royce                   Ghost  2014  premium unleaded (required)   
5284   Rolls-Royce                   Ghost  2014  premium unleaded (required)   
7443   Rolls-Royce               Park Ward  2001  premium unleaded (required)   
7444   Rolls-Royce               Park Ward  2002  premium unleaded (required)   
7553   Rolls-Royce           Phantom Coupe  2014  premium unleaded (required)   
7554   Rolls-Royce           Phantom Coupe  2015  premium unleaded (required)   
7555   Rolls-Royce           Phantom Coupe  2016  premium unleaded (required)   
7556   Rolls-Royce  Phantom Drophead Coupe  2014  premium unleaded (required)   
7557   Rolls-Royce  Phantom Drophead Coupe  2015  premium unleaded (required)   
7558   Rolls-Royce  Phantom Drophead Coupe  2016  premium unleaded (required)   
7559   Rolls-Royce                 Phantom  2014  premium unleaded (required)   
7560   Rolls-Royce                 Phantom  2014  premium unleaded (required)   
7561   Rolls-Royce                 Phantom  2015  premium unleaded (required)   
7562   Rolls-Royce                 Phantom  2015  premium unleaded (required)   
7563   Rolls-Royce                 Phantom  2016  premium unleaded (required)   
7564   Rolls-Royce                 Phantom  2016  premium unleaded (required)   
9431   Rolls-Royce           Silver Seraph  2001  premium unleaded (required)   
9432   Rolls-Royce           Silver Seraph  2002  premium unleaded (required)   
11448  Rolls-Royce                  Wraith  2014  premium unleaded (required)   
11449  Rolls-Royce                  Wraith  2015  premium unleaded (required)   
11450  Rolls-Royce                  Wraith  2016  premium unleaded (required)   

       Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921       325.0               8.0         AUTOMATIC  rear wheel drive   
3505       563.0              12.0         AUTOMATIC  rear wheel drive   
5275       563.0              12.0         AUTOMATIC  rear wheel drive   
5276       563.0              12.0         AUTOMATIC  rear wheel drive   
5277       563.0              12.0         AUTOMATIC  rear wheel drive   
5278       563.0              12.0         AUTOMATIC  rear wheel drive   
5279       563.0              12.0         AUTOMATIC  rear wheel drive   
5280       563.0              12.0         AUTOMATIC  rear wheel drive   
5281       563.0              12.0         AUTOMATIC  rear wheel drive   
5282       563.0              12.0         AUTOMATIC  rear wheel drive   
5283       563.0              12.0         AUTOMATIC  rear wheel drive   
5284       563.0              12.0         AUTOMATIC  rear wheel drive   
7443       322.0              12.0         AUTOMATIC  rear wheel drive   
7444       322.0              12.0         AUTOMATIC  rear wheel drive   
7553       453.0              12.0         AUTOMATIC  rear wheel drive   
7554       453.0              12.0         AUTOMATIC  rear wheel drive   
7555       453.0              12.0         AUTOMATIC  rear wheel drive   
7556       453.0              12.0         AUTOMATIC  rear wheel drive   
7557       453.

In [171]:
RR_3_feat=Rolls_Royce[["Engine HP","Engine Cylinders", "highway MPG" ]]
RR_3_feat

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [172]:
RR_3_feat=RR_3_feat.drop_duplicates()
RR_3_feat

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [173]:
X = RR_3_feat.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [174]:
XT = X.T
XT

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [175]:
XTX = XT.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [176]:
XTX_INV = np.linalg.inv(XTX)
XTX_INV

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [177]:
#Sum of elements of the inverse matrix
XTX_INV.sum()

0.032212320677486125

In [178]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [179]:
c = XTX_INV.dot(XT)
c


array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [180]:
w = c.dot(y)

In [181]:
w

array([ 0.19989598, 31.02612262, 31.65378877])

In [182]:
#value of the first element of w
w[0]

0.19989598183188978