In [60]:
#Importing Libraries
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [62]:
#data_path
data = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/AB_NYC_2019.csv'

In [64]:
#storing the data
!wget $data -O data-week_-3.csv

--2021-09-27 13:48:04--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/AB_NYC_2019.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7077973 (6.8M) [text/plain]
Saving to: 'data-week_-3.csv'

     0K .......... .......... .......... .......... ..........  0% 1.41M 5s
    50K .......... .......... .......... .......... ..........  1% 2.24M 4s
   100K .......... .......... .......... .......... ..........  2% 2.98M 3s
   150K .......... .......... .......... .......... ..........  2% 2.95M 3s
   200K .......... .......... .......... .......... ..........  3% 2.80M 3s
   250K .......... .......... .......... .......... ..........  4% 3.95M 3s
   300K .......... .......... .......... .......... ..........  5% 3.25M 3s
   350K .......... ....

In [66]:
#reading the data
df = pd.read_csv('data-week_-3.csv')
df.head()



id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237   
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377   
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190   
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976   
4        Laura           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19   
1  Entire home/apt    225               1                 45  2019-05-21   
2     Private room    150               3                  0         NaN   
3  Entire home/apt     89               1                270  2019-07-05   
4  Entire home/apt     80              10                  9  2018-11-19   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2                NaN                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0

In [68]:
#replacing_columns_with_lowercase
df.columns = df.columns.str.lower().str.replace(' ', '_')

categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')



In [70]:
df

id                                               name   host_id  \
0          2539                 clean_&_quiet_apt_home_by_the_park      2787   
1          2595                              skylit_midtown_castle      2845   
2          3647                the_village_of_harlem....new_york_!      4632   
3          3831                    cozy_entire_floor_of_brownstone      4869   
4          5022   entire_apt:_spacious_studio/loft_by_central_park      7192   
...         ...                                                ...       ...   
48890  36484665    charming_one_bedroom_-_newly_renovated_rowhouse   8232441   
48891  36485057      affordable_room_in_bushwick/east_williamsburg   6570630   
48892  36485431            sunny_studio_at_historical_neighborhood  23492952   
48893  36485609               43rd_st._time_square-cozy_single_bed  30985759   
48894  36487245  trendy_duplex_in_the_very_heart_of_hell's_kitchen  68119814   

           host_name neighbourhood_group       neighbourhood  latitude  \
0               john            brooklyn          kensington  40.64749   
1           jennifer           manhattan             midtown  40.75362   
2          elisabeth           manhattan              harlem  40.80902   
3        lisaroxanne            brooklyn        clinton_hill  40.68514   
4              laura           manhattan         east_harlem  40.79851   
...              ...                 ...                 ...       ...   
48890        sabrina            brooklyn  bedford-stuyvesant  40.67853   
48891        marisol            brooklyn            bushwick  40.70184   
48892  ilgar_&_aysel           manhattan              harlem  40.81475   
48893            taz           manhattan      hell's_kitchen  40.75751   
48894     christophe           manhattan      hell's_kitchen  40.76404   

       longitude        room_type  price  minimum_nights  number_of_reviews  \
0      -73.97237     private_room    149               1                  9   
1      -73.98377  entire_home/apt    225               1                 45   
2      -73.94190     private_room    150               3                  0   
3      -73.95976  entire_home/apt     89               1                270   
4      -73.94399  entire_home/apt     80              10                  9   
...          ...              ...    ...             ...                ...   
48890  -73.94995     private_room     70               2                  0   
48891  -73.93317     private_room     40               4                  0   
48892  -73.94867  entire_home/apt    115              10                  0   
48893  -73.99112      shared_room     55               1                  0   
48894  -73.98933     private_room     90               7                  0   

      last_review  reviews_per_month  calculated_host_listings_count  \
0      2018-10-19               0.21                               6   
1      2019-05-21               0.38                               2   
2             NaN                NaN                               1   
3      2019-07-05               4.64                               1   
4      2018-11-19               0.10                               1   
...           ...                ...                             ...   
48890         NaN                NaN                               2   
48891         NaN                NaN                               2   
48892         NaN                NaN                               1   
48893         NaN                NaN                               6   
48894         NaN                NaN                               1   

       availability_365  
0                   365  
1                   355  
2                   365  
3                   194  
4                     0  
...                 ...  
48890                 9  
48891                36  
48892                27  
48893                 2  
48894                23  

[48895 rows x 16 columns]

In [72]:
df.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [74]:
#filling missing values with 0
df = df.fillna(0)

In [76]:
df

id                                               name   host_id  \
0          2539                 clean_&_quiet_apt_home_by_the_park      2787   
1          2595                              skylit_midtown_castle      2845   
2          3647                the_village_of_harlem....new_york_!      4632   
3          3831                    cozy_entire_floor_of_brownstone      4869   
4          5022   entire_apt:_spacious_studio/loft_by_central_park      7192   
...         ...                                                ...       ...   
48890  36484665    charming_one_bedroom_-_newly_renovated_rowhouse   8232441   
48891  36485057      affordable_room_in_bushwick/east_williamsburg   6570630   
48892  36485431            sunny_studio_at_historical_neighborhood  23492952   
48893  36485609               43rd_st._time_square-cozy_single_bed  30985759   
48894  36487245  trendy_duplex_in_the_very_heart_of_hell's_kitchen  68119814   

           host_name neighbourhood_group       neighbourhood  latitude  \
0               john            brooklyn          kensington  40.64749   
1           jennifer           manhattan             midtown  40.75362   
2          elisabeth           manhattan              harlem  40.80902   
3        lisaroxanne            brooklyn        clinton_hill  40.68514   
4              laura           manhattan         east_harlem  40.79851   
...              ...                 ...                 ...       ...   
48890        sabrina            brooklyn  bedford-stuyvesant  40.67853   
48891        marisol            brooklyn            bushwick  40.70184   
48892  ilgar_&_aysel           manhattan              harlem  40.81475   
48893            taz           manhattan      hell's_kitchen  40.75751   
48894     christophe           manhattan      hell's_kitchen  40.76404   

       longitude        room_type  price  minimum_nights  number_of_reviews  \
0      -73.97237     private_room    149               1                  9   
1      -73.98377  entire_home/apt    225               1                 45   
2      -73.94190     private_room    150               3                  0   
3      -73.95976  entire_home/apt     89               1                270   
4      -73.94399  entire_home/apt     80              10                  9   
...          ...              ...    ...             ...                ...   
48890  -73.94995     private_room     70               2                  0   
48891  -73.93317     private_room     40               4                  0   
48892  -73.94867  entire_home/apt    115              10                  0   
48893  -73.99112      shared_room     55               1                  0   
48894  -73.98933     private_room     90               7                  0   

      last_review  reviews_per_month  calculated_host_listings_count  \
0      2018-10-19               0.21                               6   
1      2019-05-21               0.38                               2   
2               0               0.00                               1   
3      2019-07-05               4.64                               1   
4      2018-11-19               0.10                               1   
...           ...                ...                             ...   
48890           0               0.00                               2   
48891           0               0.00                               2   
48892           0               0.00                               1   
48893           0               0.00                               6   
48894           0               0.00                               1   

       availability_365  
0                   365  
1                   355  
2                   365  
3                   194  
4                     0  
...                 ...  
48890                 9  
48891                36  
48892                27  
48893                 2  
48894                23  

[48895 rows x 16 columns]

In [78]:
#train_test_split
from sklearn.model_selection import train_test_split



In [80]:
#splitting the datas into train/val/test
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [82]:
len(df_train), len(df_val), len(df_test)

(29337, 9779, 9779)

In [84]:
#reset_the_index
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)



In [86]:
#target_variables
y_train = df_train.price.values
y_val = df_val.price.values
y_test = df_test.price.values

#delete_target_variable_from_train/val/test
del df_train['price']
del df_val['price']
del df_test['price']



Question 1

In [88]:
#Most frequent observation (mode) for the column 'neighbourhood_group'
df_train.neighbourhood_group.mode()

0    manhattan
dtype: object

In [90]:
#numerical_features
numerical = ['latitude','longitude','minimum_nights','number_of_reviews',
'reviews_per_month','calculated_host_listings_count','availability_365']

In [92]:
#categorical_features
categorical = ['neighbourhood_group','room_type']

Question 2

In [93]:
#Calculating Correlation between numerical features
def corre():

    numerical = ['latitude','longitude','minimum_nights','number_of_reviews',
    'reviews_per_month','calculated_host_listings_count','availability_365']

    cor_list = []
    cor_feat = []

    for i in numerical:
        (df_train[numerical].corrwith(df_train[numerical][i]))
        cor_feat.append("Correlated_with %s" %i)
        cor_list.append((df_train[numerical].corrwith(df_train[numerical][i])))
        


    return cor_feat,cor_list

In [94]:
correlated_feature,correlation_list = corre()

In [95]:
#correlation_between_different_numerical_features
correlation_list[:]

[latitude                          1.000000
 longitude                         0.080301
 minimum_nights                    0.027441
 number_of_reviews                -0.006246
 reviews_per_month                -0.007159
 calculated_host_listings_count    0.019375
 availability_365                 -0.005891
 dtype: float64,
 latitude                          0.080301
 longitude                         1.000000
 minimum_nights                   -0.060660
 number_of_reviews                 0.055084
 reviews_per_month                 0.134642
 calculated_host_listings_count   -0.117041
 availability_365                  0.083666
 dtype: float64,
 latitude                          0.027441
 longitude                        -0.060660
 minimum_nights                    1.000000
 number_of_reviews                -0.076020
 reviews_per_month                -0.120703
 calculated_host_listings_count    0.118647
 availability_365                  0.138901
 dtype: float64,
 latitude                

In [96]:
correlated_feature

['Correlated_with latitude',
 'Correlated_with longitude',
 'Correlated_with minimum_nights',
 'Correlated_with number_of_reviews',
 'Correlated_with reviews_per_month',
 'Correlated_with calculated_host_listings_count',
 'Correlated_with availability_365']

In [97]:
len(correlation_list)

7

In [98]:
#storing the correlation values as a list
cor_val = []
for i in range(7):
    cor_val.append(correlation_list[i].values)


In [99]:

cor_val

[array([ 1.        ,  0.08030088,  0.02744122, -0.00624562, -0.00715934,
         0.01937516, -0.00589119]),
 array([ 0.08030088,  1.        , -0.06065967,  0.05508445,  0.13464216,
        -0.11704069,  0.0836655 ]),
 array([ 0.02744122, -0.06065967,  1.        , -0.0760198 , -0.12070279,
         0.11864675,  0.13890125]),
 array([-0.00624562,  0.05508445, -0.0760198 ,  1.        ,  0.5903739 ,
        -0.07316723,  0.17447712]),
 array([-0.00715934,  0.13464216, -0.12070279,  0.5903739 ,  1.        ,
        -0.04876682,  0.16537592]),
 array([ 0.01937516, -0.11704069,  0.11864675, -0.07316723, -0.04876682,
         1.        ,  0.22591309]),
 array([-0.00589119,  0.0836655 ,  0.13890125,  0.17447712,  0.16537592,
         0.22591309,  1.        ])]

In [100]:
#storing the corelation as a pandas data frame
correlation_df = pd.DataFrame(cor_val,index = correlated_feature,columns = correlated_feature)

In [101]:
#correlation matrix between numerical features
correlation_df

Correlated_with latitude  \
Correlated_with latitude                                        1.000000   
Correlated_with longitude                                       0.080301   
Correlated_with minimum_nights                                  0.027441   
Correlated_with number_of_reviews                              -0.006246   
Correlated_with reviews_per_month                              -0.007159   
Correlated_with calculated_host_listings_count                  0.019375   
Correlated_with availability_365                               -0.005891   

                                                Correlated_with longitude  \
Correlated_with latitude                                         0.080301   
Correlated_with longitude                                        1.000000   
Correlated_with minimum_nights                                  -0.060660   
Correlated_with number_of_reviews                                0.055084   
Correlated_with reviews_per_month                                0.134642   
Correlated_with calculated_host_listings_count                  -0.117041   
Correlated_with availability_365                                 0.083666   

                                                Correlated_with minimum_nights  \
Correlated_with latitude                                              0.027441   
Correlated_with longitude                                            -0.060660   
Correlated_with minimum_nights                                        1.000000   
Correlated_with number_of_reviews                                    -0.076020   
Correlated_with reviews_per_month                                    -0.120703   
Correlated_with calculated_host_listings_count                        0.118647   
Correlated_with availability_365                                      0.138901   

                                                Correlated_with number_of_reviews  \
Correlated_with latitude                                                -0.006246   
Correlated_with longitude                                                0.055084   
Correlated_with minimum_nights                                          -0.076020   
Correlated_with number_of_reviews                                        1.000000   
Correlated_with reviews_per_month                                        0.590374   
Correlated_with calculated_host_listings_count                          -0.073167   
Correlated_with availability_365                                         0.174477   

                                                Correlated_with reviews_per_month  \
Correlated_with latitude                                                -0.007159   
Correlated_with longitude                                                0.134642   
Correlated_with minimum_nights                                          -0.120703   
Correlated_with number_of_reviews                                        0.590374   
Correlated_with reviews_per_month                                        1.000000   
Correlated_with calculated_host_listings_count                          -0.048767   
Correlated_with availability_365                                         0.165376   

                                                Correlated_with calculated_host_listings_count  \
Correlated_with latitude                                                              0.019375   
Correlated_with longitude                                                            -0.117041   
Correlated_with minimum_nights                                                        0.118647   
Correlated_with number_of_reviews                                                    -0.073167   
Correlated_with reviews_per_month                                                    -0.048767   
Correlated_with calculated_host_listings_count                                        1.000000   
Correlated_with availability_365                                                      0.225913   

                  

In [102]:
correlation_df['Correlated_with reviews_per_month'].index[3]

'Correlated_with number_of_reviews'

In [103]:
#Two features that have the biggest correlation in this dataset
correlation_df['Correlated_with reviews_per_month']
values_cor= []
for i in correlation_df['Correlated_with reviews_per_month'].values:
    if i ==1:
        print("Ignored 1")
    else:
        values_cor.append(i)
print("The biggest correlation between two features is : {} \nThe feature is Correlated_with reviews_per_month and {}".format(max(values_cor),correlation_df['Correlated_with reviews_per_month'].index[(np.where(values_cor == max(values_cor))[0][0])]))

Ignored 1
The biggest correlation between two features is : 0.5903739015971649 
The feature is Correlated_with reviews_per_month and Correlated_with number_of_reviews


Question 3

In [104]:
#importing mutual_info_score
from sklearn.metrics import mutual_info_score

In [105]:
#Make price binary
above_average = (y_train>=152).astype('int')

In [106]:
above_average

array([0, 0, 0, ..., 1, 0, 0])

In [107]:
len(above_average)

29337

In [108]:
#Mutual information score for neighbourhood_group
round(mutual_info_score(df_train.neighbourhood_group, above_average),2)

0.05

In [109]:
#Mutual information score for room_type
round(mutual_info_score(df_train.room_type, above_average),2)

0.14

In [110]:
#train data with only numerical and caegorical features
df_train[categorical + numerical]

neighbourhood_group        room_type  latitude  longitude  \
0                brooklyn  entire_home/apt  40.72760  -73.94495   
1               manhattan     private_room  40.70847  -74.00498   
2                   bronx  entire_home/apt  40.83149  -73.92766   
3                brooklyn  entire_home/apt  40.66448  -73.99407   
4               manhattan     private_room  40.74118  -74.00012   
...                   ...              ...       ...        ...   
29332            brooklyn     private_room  40.71748  -73.95685   
29333            brooklyn     private_room  40.66397  -73.98538   
29334           manhattan     private_room  40.79994  -73.97001   
29335            brooklyn     private_room  40.69585  -73.96344   
29336            brooklyn  entire_home/apt  40.64438  -73.95484   

       minimum_nights  number_of_reviews  reviews_per_month  \
0                   3                 29               0.70   
1                   1                  0               0.00   
2                  40                  0               0.00   
3                   2                  3               0.08   
4                   1                 48               1.80   
...               ...                ...                ...   
29332               6                  5               0.13   
29333               1                  7               0.17   
29334               1                  1               0.64   
29335              60                  0               0.00   
29336               7                 15               0.49   

       calculated_host_listings_count  availability_365  
0                                  13                50  
1                                   1                 7  
2                                   1                 0  
3                                   1                 0  
4                                   2                67  
...                               ...               ...  
29332                               1                 0  
29333                               2                 0  
29334                               1                88  
29335                               1                 0  
29336                               2               281  

[29337 rows x 9 columns]

In [111]:
#validation data with only numerical and caegorical features
df_val[categorical + numerical]

neighbourhood_group        room_type  latitude  longitude  \
0               brooklyn     private_room  40.70239  -73.92931   
1               brooklyn  entire_home/apt  40.68498  -73.96618   
2               brooklyn  entire_home/apt  40.66911  -73.94824   
3              manhattan     private_room  40.79767  -73.96114   
4              manhattan  entire_home/apt  40.76075  -73.99893   
...                  ...              ...       ...        ...   
9774           manhattan  entire_home/apt  40.75974  -73.98924   
9775               bronx      shared_room  40.80952  -73.93005   
9776           manhattan     private_room  40.73058  -73.98286   
9777            brooklyn     private_room  40.68858  -73.95387   
9778           manhattan  entire_home/apt  40.81882  -73.94680   

      minimum_nights  number_of_reviews  reviews_per_month  \
0                  1                 35               1.80   
1                 14                  4               0.11   
2                  3                153               2.64   
3                  3                  2               0.02   
4                 30                  0               0.00   
...              ...                ...                ...   
9774               4                  2               0.14   
9775               1                 17               1.79   
9776               1                  4               0.10   
9777               1                  0               0.00   
9778               1                  1               0.02   

      calculated_host_listings_count  availability_365  
0                                  1                52  
1                                  2               343  
2                                  1               260  
3                                  3                 0  
4                                 18               365  
...                              ...               ...  
9774                               1                 5  
9775                               7                83  
9776                               1                 0  
9777                               1                 0  
9778                               1                 0  

[9779 rows x 9 columns]

Question 4

In [112]:
#one-hot encoding using DictVectorizer
from sklearn.feature_extraction import DictVectorizer



In [113]:
#DictVectorizer for train and val
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [114]:
#Importing Logistic Regression
from sklearn.linear_model import LogisticRegression

In [115]:
#fitting the model
model = LogisticRegression(solver='liblinear', C=1.0, random_state=42)
#
model.fit(X_train, above_average)

LogisticRegression(random_state=42, solver='liblinear')

In [116]:
model.coef_[0].round(3)

array([ 3.000e-03,  4.000e-03, -5.815e+00, -3.165e+00, -1.100e-02,
       -8.200e-02,  1.250e-01,  1.575e+00, -3.000e-02, -1.679e+00,
       -3.000e-03, -4.200e-02,  1.959e+00, -8.170e-01, -1.233e+00])

In [117]:
#predicting the model with validation data
y_pred_val = model.predict(X_val)

In [118]:
y_pred_val

array([0, 1, 0, ..., 0, 0, 1])

In [119]:
#making validation target variable binary
price_val_binary = (y_val>=152).astype('int')

In [120]:
(price_val_binary)

array([0, 0, 1, ..., 0, 0, 0])

In [121]:
#orig_accuracy
#Accuracy of the model
orig_accuracy = (price_val_binary==y_pred_val).mean()
orig_accuracy

0.7907761529808774

Question 5

In [122]:
#creating new data frames for feature elimination
df1_train = df_train[categorical+numerical]
df1_val = df_val[categorical+numerical]

In [123]:
df1_val

neighbourhood_group        room_type  latitude  longitude  \
0               brooklyn     private_room  40.70239  -73.92931   
1               brooklyn  entire_home/apt  40.68498  -73.96618   
2               brooklyn  entire_home/apt  40.66911  -73.94824   
3              manhattan     private_room  40.79767  -73.96114   
4              manhattan  entire_home/apt  40.76075  -73.99893   
...                  ...              ...       ...        ...   
9774           manhattan  entire_home/apt  40.75974  -73.98924   
9775               bronx      shared_room  40.80952  -73.93005   
9776           manhattan     private_room  40.73058  -73.98286   
9777            brooklyn     private_room  40.68858  -73.95387   
9778           manhattan  entire_home/apt  40.81882  -73.94680   

      minimum_nights  number_of_reviews  reviews_per_month  \
0                  1                 35               1.80   
1                 14                  4               0.11   
2                  3                153               2.64   
3                  3                  2               0.02   
4                 30                  0               0.00   
...              ...                ...                ...   
9774               4                  2               0.14   
9775               1                 17               1.79   
9776               1                  4               0.10   
9777               1                  0               0.00   
9778               1                  1               0.02   

      calculated_host_listings_count  availability_365  
0                                  1                52  
1                                  2               343  
2                                  1               260  
3                                  3                 0  
4                                 18               365  
...                              ...               ...  
9774                               1                 5  
9775                               7                83  
9776                               1                 0  
9777                               1                 0  
9778                               1                 0  

[9779 rows x 9 columns]

In [124]:
df1_train

neighbourhood_group        room_type  latitude  longitude  \
0                brooklyn  entire_home/apt  40.72760  -73.94495   
1               manhattan     private_room  40.70847  -74.00498   
2                   bronx  entire_home/apt  40.83149  -73.92766   
3                brooklyn  entire_home/apt  40.66448  -73.99407   
4               manhattan     private_room  40.74118  -74.00012   
...                   ...              ...       ...        ...   
29332            brooklyn     private_room  40.71748  -73.95685   
29333            brooklyn     private_room  40.66397  -73.98538   
29334           manhattan     private_room  40.79994  -73.97001   
29335            brooklyn     private_room  40.69585  -73.96344   
29336            brooklyn  entire_home/apt  40.64438  -73.95484   

       minimum_nights  number_of_reviews  reviews_per_month  \
0                   3                 29               0.70   
1                   1                  0               0.00   
2                  40                  0               0.00   
3                   2                  3               0.08   
4                   1                 48               1.80   
...               ...                ...                ...   
29332               6                  5               0.13   
29333               1                  7               0.17   
29334               1                  1               0.64   
29335              60                  0               0.00   
29336               7                 15               0.49   

       calculated_host_listings_count  availability_365  
0                                  13                50  
1                                   1                 7  
2                                   1                 0  
3                                   1                 0  
4                                   2                67  
...                               ...               ...  
29332                               1                 0  
29333                               2                 0  
29334                               1                88  
29335                               1                 0  
29336                               2               281  

[29337 rows x 9 columns]

In [125]:
 features1 = categorical + numerical

In [126]:
features1[:]

['neighbourhood_group',
 'room_type',
 'latitude',
 'longitude',
 'minimum_nights',
 'number_of_reviews',
 'reviews_per_month',
 'calculated_host_listings_count',
 'availability_365']

In [127]:
#removing each feature individually and storing in new data frames
def feat_remove():

    features = categorical + numerical

    feat_train = []
    feat_val = []
    feat_i = []
    
    for i in features:
      feat_train.append(df1_train.drop([i],axis=1))
      feat_val.append(df1_val.drop([i],axis=1))
      feat_i.append(i)

    return feat_train,feat_val,feat_i

In [128]:
#data frames with individual features being removed to train and compute the model
feat_train,feat_val,feat_removed = feat_remove()

In [129]:
#neighbourwood_group removed in first train data frame
feat_train[0]

room_type  latitude  longitude  minimum_nights  \
0      entire_home/apt  40.72760  -73.94495               3   
1         private_room  40.70847  -74.00498               1   
2      entire_home/apt  40.83149  -73.92766              40   
3      entire_home/apt  40.66448  -73.99407               2   
4         private_room  40.74118  -74.00012               1   
...                ...       ...        ...             ...   
29332     private_room  40.71748  -73.95685               6   
29333     private_room  40.66397  -73.98538               1   
29334     private_room  40.79994  -73.97001               1   
29335     private_room  40.69585  -73.96344              60   
29336  entire_home/apt  40.64438  -73.95484               7   

       number_of_reviews  reviews_per_month  calculated_host_listings_count  \
0                     29               0.70                              13   
1                      0               0.00                               1   
2                      0               0.00                               1   
3                      3               0.08                               1   
4                     48               1.80                               2   
...                  ...                ...                             ...   
29332                  5               0.13                               1   
29333                  7               0.17                               2   
29334                  1               0.64                               1   
29335                  0               0.00                               1   
29336                 15               0.49                               2   

       availability_365  
0                    50  
1                     7  
2                     0  
3                     0  
4                    67  
...                 ...  
29332                 0  
29333                 0  
29334                88  
29335                 0  
29336               281  

[29337 rows x 8 columns]

In [130]:
#neighbourwood_group removed in first val data frame
feat_val[0]

room_type  latitude  longitude  minimum_nights  number_of_reviews  \
0        private_room  40.70239  -73.92931               1                 35   
1     entire_home/apt  40.68498  -73.96618              14                  4   
2     entire_home/apt  40.66911  -73.94824               3                153   
3        private_room  40.79767  -73.96114               3                  2   
4     entire_home/apt  40.76075  -73.99893              30                  0   
...               ...       ...        ...             ...                ...   
9774  entire_home/apt  40.75974  -73.98924               4                  2   
9775      shared_room  40.80952  -73.93005               1                 17   
9776     private_room  40.73058  -73.98286               1                  4   
9777     private_room  40.68858  -73.95387               1                  0   
9778  entire_home/apt  40.81882  -73.94680               1                  1   

      reviews_per_month  calculated_host_listings_count  availability_365  
0                  1.80                               1                52  
1                  0.11                               2               343  
2                  2.64                               1               260  
3                  0.02                               3                 0  
4                  0.00                              18               365  
...                 ...                             ...               ...  
9774               0.14                               1                 5  
9775               1.79                               7                83  
9776               0.10                               1                 0  
9777               0.00                               1                 0  
9778               0.02                               1                 0  

[9779 rows x 8 columns]

In [131]:
#removed feature
feat_removed[0]

'neighbourhood_group'

In [132]:
#function for storing the accuracy values using feature elimination technique 
def train_model(ft,fv,fr):
    

    from sklearn.feature_extraction import DictVectorizer


    dv = DictVectorizer(sparse=False)

    train_dict = ft.to_dict(orient='records')
    X_train = dv.fit_transform(train_dict)

    val_dict = fv.to_dict(orient='records')
    X_val = dv.transform(val_dict)

    from sklearn.linear_model import LogisticRegression

    model = LogisticRegression(solver='liblinear', random_state=42)
    
    model.fit(X_train, above_average)
    


    
    y_pred_binar = model.predict(X_val)
    
    
    price_val_binary = (y_val>=152).astype('int')

   
    accuracy_y_pred_val = (price_val_binary==y_pred_binar).mean()
    
    return accuracy_y_pred_val,fr

In [133]:

#function for storing the accuracy values using feature elimination technique in accuracy_val = [] list
def feat_remov_accuracy(ft,fv,fr):

    accuracy_val = []

    for i in range(9):
        accuracy_val.append(train_model(ft[i],fv[i],fr[i]))
        

    return accuracy_val


In [59]:
#storing the calculated accuracy value differ
accuracy_values = feat_remov_accuracy(feat_train,feat_val,feat_removed)

In [61]:
#Feature selection - the smallest difference in accuracy
accuracy_values

[(0.7498721750690255, 'neighbourhood_group'),
 (0.7286021065548625, 'room_type'),
 (0.7867880151344718, 'latitude'),
 (0.7869925350240311, 'longitude'),
 (0.7914919725943348, 'minimum_nights'),
 (0.7911851927599959, 'number_of_reviews'),
 (0.7907761529808774, 'reviews_per_month'),
 (0.7896512935883014, 'calculated_host_listings_count'),
 (0.7812659781163718, 'availability_365')]

In [63]:
#For loop calculating and storing the difference between original accuracy and accuracy calculated with feature elimination technique
accuracy_dif = []
removed_feature = []
orig_accuracy

for i in range(9):
        diff = orig_accuracy - accuracy_values[i][0]
        accuracy_dif.append(diff)
        removed_feature.append(accuracy_values[i][1])

        

In [65]:
#accuracy difference and corrsponding feature being removed
print("The accuracy difference values with feature elimination technique are : {} \nThe removed features of the corresponding accuracy difference values are : {}\n".format(accuracy_dif,removed_feature))

print("The smallest difference out of all the feature is : {} \nThe corresponding feature being removed is: {} \n\n ".format(min(accuracy_dif),removed_feature[np.where(accuracy_dif == min(accuracy_dif))[0][0]]))

print("The smallest different out of "'neighbourhood_group'"," 'room_type'","'number_of_reviews'"," 'reviews_per_month'" is : {} \nThe corresponding removed feature is :{}".format(accuracy_dif[5],removed_feature[5]))


The accuracy difference values with feature elimination technique are : [0.04090397791185196, 0.062174046426014984, 0.003988137846405615, 0.0037836179568463413, -0.0007158196134573469, -0.00040903977911843636, 0.0, 0.0011248593925760053, 0.009510174864505672] 
The removed features of the corresponding accuracy difference values are : ['neighbourhood_group', 'room_type', 'latitude', 'longitude', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365']

The smallest difference out of all the feature is : -0.0007158196134573469 
The corresponding feature being removed is: minimum_nights 

 
The smallest different out of neighbourhood_group,room_type,number_of_reviews,reviews_per_month is : -0.00040903977911843636 
The corresponding removed feature is :number_of_reviews


Question 6

In [67]:
#Applying the logarithmic transformation to target variable price for all sets
y_train_log = np.log1p(y_train)
y_val_log = np.log1p(y_val)
y_test_log = np.log1p(y_test)

In [69]:
y_train_log

array([4.60517019, 4.06044301, 4.26267988, ..., 5.70378247, 4.18965474,
       4.53259949])

In [71]:
#function for calculating rmse
def rmse(y,y_pred):
    se = (y - y_pred)**2
    mse = se.mean()
    return np.sqrt(mse)

In [73]:
#function for calculating prediction values for different alpha parameters in Ridge regression model
def train_ridge_model(tr,val,alpha):
    

    from sklearn.feature_extraction import DictVectorizer


    dv = DictVectorizer(sparse=False)

    train_dict = tr[categorical + numerical].to_dict(orient='records')
    X_train = dv.fit_transform(train_dict)

    val_dict = val[categorical + numerical].to_dict(orient='records')
    X_val = dv.transform(val_dict)

    from sklearn.linear_model import Ridge

    model = Ridge(alpha = alpha)
    
    model.fit(X_train, y_train_log)
    


    
    y_pred = model.predict(X_val)
    
    
    price_val_binary = (y_val_log>=152).astype('int')

   
    accuracy_y_pred_val = (price_val_binary==y_pred).mean()
    
    return y_pred,alpha

In [75]:
#For loop storing prediction values for different alpha parameters in Ridge regression model in y_pred_values = []
y_pred_values = []
alpha_values  = []

for i in [0,0.01,0.1,1,10]:
    y_pred,alpha = train_ridge_model(df_train,df_val,i)
    y_pred_values.append(y_pred)
    alpha_values.append(i)
    

C:\Users\subra\anaconda3\envs\tf2.6\lib\site-packages\sklearn\linear_model\_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=4.74051e-21): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,


In [77]:
#Ridge regression model prediction values and corresponding alpha values

print("The prediction values for Ridge regression model are : {} \n \nThe corresponding Alpha Parameters are : {}".format(y_pred_values,alpha_values))



The prediction values for Ridge regression model are : [array([4.11403292, 5.21397566, 5.01012088, ..., 4.5595318 , 4.19405383,
       5.14431264]), array([4.11405448, 5.21395699, 5.01012603, ..., 4.5595196 , 4.19404933,
       5.14435076]), array([4.1142478 , 5.21378968, 5.01017209, ..., 4.55940994, 4.19400898,
       5.14469281]), array([4.116111  , 5.21218878, 5.01060186, ..., 4.55832635, 4.19362144,
       5.14801035]), array([4.12973827, 5.20108005, 5.01293916, ..., 4.54893373, 4.19086998,
       5.17337529])] 
 
The corresponding Alpha Parameters are : [0, 0.01, 0.1, 1, 10]


In [79]:
y_pred_values

[array([4.11403292, 5.21397566, 5.01012088, ..., 4.5595318 , 4.19405383,
        5.14431264]),
 array([4.11405448, 5.21395699, 5.01012603, ..., 4.5595196 , 4.19404933,
        5.14435076]),
 array([4.1142478 , 5.21378968, 5.01017209, ..., 4.55940994, 4.19400898,
        5.14469281]),
 array([4.116111  , 5.21218878, 5.01060186, ..., 4.55832635, 4.19362144,
        5.14801035]),
 array([4.12973827, 5.20108005, 5.01293916, ..., 4.54893373, 4.19086998,
        5.17337529])]

In [81]:
len(y_val_log)

9779

In [83]:
#rounding validation set
y_val_log_rnd = []
for i in y_val_log:
    i = round(i,3)
    y_val_log_rnd.append(i)

In [85]:
len(y_val_log_rnd)

9779

In [87]:
len(y_pred_values[0])

9779

In [89]:
#Computing and storing RMSE scores for different Alpha parameters used in Ridge Regression
rmse_scores = []
for i in y_pred_values:
    score = round(rmse(y_val_log_rnd,i),3)
    rmse_scores.append(score)
    


In [91]:
#RMSE Scores for different Alpha Parameters
print("The different RMSE scores are : {} \n \nThe corresponding Alpha Parameters are : {}".format(rmse_scores,alpha_values))


The different RMSE scores are : [0.497, 0.497, 0.497, 0.497, 0.498] 
 
The corresponding Alpha Parameters are : [0, 0.01, 0.1, 1, 10]
